openapi: 3.0.1
info:
  title: 受講生管理システム
  description: 受講生及び受講コースの登録・更新・検索を行います。
  version: "0.0"

paths:
  /students:
    post:
      summary: 受講生と受講コースを登録する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDetailForm'
      responses:
        '200':
          description: 登録成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetailResponse'

    put:
      summary: 受講生と受講コースを更新する
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDetailForm'
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetailResponse'

  /students/{studentId}:
    get:
      summary: 受講生情報をIDで取得する
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 検索成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetailResponse'

components:
  schemas:
    StudentDetailForm:
      type: object
      required: [ student, studentCourseList ]
      properties:
        student:
          $ref: '#/components/schemas/StudentForm'
        studentCourseList:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourseForm'

    StudentForm:
      type: object
      properties:
        studentId:
          type: integer
          example: 1
        fullname:
          type: string
          example: 佐藤花子
        kanaName:
          type: string
          example: さとうはなこ
        nickname:
          type: string
          example: ハナ
        email:
          type: string
          format: email
          example: hanako@example.com
        area:
          type: string
          example: 東京都品川区
        telephone:
          type: string
          example: 090-1234-5678
        age:
          type: integer
          example: 25
        sex:
          type: string
          example: 女
        remark:
          type: string
          example: 転職活動中
        isDeleted:
          type: boolean
          example: false

    StudentCourseForm:
      type: object
      properties:
        courseId:
          type: integer
          example: 1
        courseName:
          type: string
          example: Javaコース
        courseEndAt:
          type: string
          format: date
          example: 2025-07-01

    StudentDetailResponse:
      type: object
      properties:
        student:
          $ref: '#/components/schemas/StudentResponse'
        studentCourseList:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourseResponse'

    StudentResponse:
      type: object
      properties:
        studentId:
          type: integer
          example: 1
        fullname:
          type: string
          example: 佐藤花子
        kanaName:
          type: string
          example: さとうはなこ
        nickname:
          type: string
          example: ハナ
        email:
          type: string
          example: hana@example.com
        area:
          type: string
          example: 東京都品川区
        telephone:
          type: string
          example: 090-1234-5678
        age:
          type: integer
          example: 25
        sex:
          type: string
          example: 女
        remark:
          type: string
          example: 転職活動中
        isDeleted:
          type: boolean
          example: false

    StudentCourseResponse:
      type: object
      properties:
        courseId:
          type: integer
          example: 1
        courseName:
          type: string
          example: Javaコース
        courseStartAt:
          type: string
          format: date
          example: 2025-01-01
        courseEndAt:
          type: string
          format: date
          example: 2025-07-01
