spring.application.name=StudentManagement
spring.datasource.url=jdbc:mysql://localhost:3306/student_management
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# MyBatisの設定
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath*:/mapper/*.xml
# ログレベルをDEBUGに設定
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=DEBUG
#logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter=DEBUG
#logging.level.org.springframework.boot.autoconfigure=ERROR