openapi: 3.0.1
info:
  title: 受講生管理システム
  description: 受講生及び受講コースの登録・更新・検索を行います。
  version: "0.0"
servers:
  - url: http://localhost:8080
    description: Local server

paths:
  /students:
    get:
      summary: アクティブな受講生詳細一覧の検索
      description: アクティブな受講生詳細の一覧を検索します。全件検索を行うので、条件指定はしません
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StudentDetail'
    post:
      summary: 受講生詳細登録
      description: 受講生の登録を行います
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDetail'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetail'
        '400':
          description: 入力値のバリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
    put:
      summary: 受講生詳細更新
      description: |
        受講生詳細の更新を行います。キャンセルフラグの更新(アクティブ⇔非アクティブ)もここで行います。
        受講生IDが登録されていない、または受講生コースIDがひとつでも受講生IDと紐づかない場合はエラーを返します。
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentDetail'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetail'
        '400':
          description: 入力値のバリデーションエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        '404':
          description: 指定された受講生IDが存在しないか、受講生コースIDが受講生IDに紐づかないときのエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /students/{studentId}:
    get:
      summary: 受講生詳細検索
      description: アクティブ・非アクティブを問わず、受講生詳細の全件から受講生IDが一致する受講生の詳細を取得します。
      parameters:
        - name: studentId
          in: path
          required: true
          schema:
            type: integer
            format: int32
          description: 受講生ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentDetail'
        '400':
          description: 受講生IDの形式が不正であったときのエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
        '404':
          description: 指定された受講生IDが存在しなかったときのエラー
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /studentAndCourses:
    get:
      summary: アクティブな受講生詳細一覧の検索(旧ver・非使用)
      description: 現在使われていないURIです。エラーを返し、正しいアドレスへのアクセスを促します
      responses:
        '404':
          description: not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

components:
  schemas:
    Student:
      type: object
      properties:
        studentId:
          type: integer
          example: 1
        fullname:
          type: string
          example: 佐藤花子
        kanaName:
          type: string
          example: さとうはなこ
        nickname:
          type: string
          example: ハナ
        email:
          type: string
          example: hanako@raisetech.com
        area:
          type: string
          example: 東京都
        telephone:
          type: string
          example: 070-0000-0000
        age:
          type: integer
          example: 20
        sex:
          type: string
          example: 女
        remark:
          type: string
          example: 転職活動中
        isDeleted:
          type: boolean
          example: false

    StudentCourse:
      type: object
      properties:
        courseId:
          type: integer
          example: 1
        courseName:
          type: string
          example: Javaコース
        studentId:
          type: integer
          example: 1
        courseStartAt:
          type: string
          format: date
          example: 2025-01-01
        courseEndAt:
          type: string
          format: date
          example: 2025-07-01

    StudentDetail:
      type: object
      properties:
        student:
          $ref: '#/components/schemas/Student'
        studentCourseList:
          type: array
          items:
            $ref: '#/components/schemas/StudentCourse'

    ErrorResponseBody:
      type: object
      properties:
        status:
          type: string
          example: BAD_REQUEST
        message:
          type: string
          example: validation error
        errors:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
